name: Delete old workflow runs

on:
  schedule:
    # Run daily at 2:34GMT+8/18:34UTC
    - cron: '34 2 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 7

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 7
