# This workflow tests the docker image by using it to compile a OpenWRT firmware

env:
  DK_IMAGE_NAME: "openwrt-buildenv"
  DK_REGISTRY: ${{secrets.docker_registry}}
  DK_USERNAME: ${{secrets.docker_username}}
  DK_PASSWORD: ${{secrets.docker_password}}
  TMATE_ENCRYPT_PASSWORD: ${{secrets.TMATE_ENCRYPT_PASSWORD}}

name: Test-OpenWRT-Buildenv-Docker-Iamge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - ".github/workflows/test.yml"
      - "scripts/test-docker.sh"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_run:
    workflows: ["Build-OpenWRT-BuildEnv-Docker-Iamge"]
    types:
      - completed


jobs:
  Test-OpenWRT-Buildenv-Docker-Iamge:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Pull the docker container and test it
      - name: Test Docker Builder
        id: test
        continue-on-error: true
        run: bash -x scripts/test-docker.sh && echo ::set-output name=status::success

      - name: "[Debug] Wait for SSH connection (timeout 5min)"
        if: steps.test.outputs.status != 'success'
        env:
          TIMEOUT_MIN: 5
        uses: tete1030/safe-debugger-action@dev
